cardfactory/urls.py
from django.urls import path


from . import views

app_name = "cardfactory"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("cartes", views.CardListView.as_view(), name="card_list"),
    path(
        "cartes_vue_compacte",
        views.CardListCompactView.as_view(),
        name="card_compact_list",
    ),
    path("cartes/<int:pk>", views.CardDetailView.as_view(), name="card_detail"),
    path("cartes/modifier_carte/<int:pk>", views.edit_card, name="edit_card"),
    path("cartes/lot/<int:pk>", views.card_list_per_batch, name="card_list_per_batch"),
    path("lots", views.batch_list, name="batch_list"),
]

fresquedata/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("cardfactory.urls")),
    path("tinymce/", include("tinymce.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cardfactory/models.py
from django.db import models
from tinymce.models import HTMLField
from file_validator.models import DjangoFileValidator


# Create your models here.


class Batch(models.Model):
    name = models.CharField("Nom du Lot", max_length=500, unique=True)
    number = models.IntegerField("Numéro de Lot", default=1)

    def __str__(self):
        return f"{self.number} : {self.name}"

    class Meta:
        ordering = ["number"]


class Card(models.Model):
    title = models.CharField("Titre", max_length=200, unique=True)
    lot = models.ForeignKey(Batch, on_delete=models.CASCADE, blank=True, null=True)
    card_number = models.IntegerField("Numéro de carte", blank=True, default=1)
    illustration = models.ImageField(
        blank=True,
        upload_to="photos/",
        validators=[
            DjangoFileValidator(
                libraries=[
                    "python_magic",
                    "filetype",
                ],  # => validation operations will be performed with python-magic and filetype libraries
                acceptable_mimes=[
                    "image/png",
                    "image/jpeg",
                    "image/jpg",
                    "image/webp",
                ],  # => The mimes you want the file to be checked based on.
                acceptable_types=["image"],
                max_upload_file_size=5242880,
            )
        ],  # => 5 MB
    )
    illustation_footnote = models.CharField(
        "Note sur l'illustration", max_length=500, blank=True
    )
    content = HTMLField("Verso de la carte", max_length=10000, blank=True)

    def __str__(self):
        return f"Lot {self.lot}, {self.title}"

cardfactory/forms.py
from django import forms
from .models import Card
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit


class CardForm(forms.ModelForm):
    class Meta:
        model = Card
        exclude = ("pk",)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = "post"

        self.helper.add_input(
            Submit(
                "submit",
                "Modifier Carte",
                css_class="m-1 btn-secondary",
            )
        )

cardfactory/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, DetailView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.http import HttpResponseRedirect

from .models import Card, Batch
from .forms import CardForm

# Create your views here.


class IndexView(TemplateView):
    template_name = "cardfactory/index.html"


class CardListView(LoginRequiredMixin, ListView):
    template_name = "cardfactory/card_list.html"
    model = Card
    context_object_name = "card_list"
    ordering = [
        "lot",
        "card_number",
    ]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["batches_list"] = Batch.objects.all()
        return context


class CardListCompactView(CardListView):
    template_name = "cardfactory/card_compact_list.html"


class CardDetailView(LoginRequiredMixin, DetailView):
    template_name = "cardfactory/card_detail.html"
    model = Card
    context_object_name = "card"


@login_required
def batch_list(request):
    template_name = "cardfactory/batch_list.html"
    batches = Batch.objects.all()
    context = {"batch_list": batches}
    return render(request, template_name, context)


@login_required
def card_list_per_batch(request, pk):
    template_name = "cardfactory/card_list.html"
    all_cards = Card.objects.all()
    batch = Batch.objects.get(pk=pk)
    queryset = all_cards.filter(lot=batch).order_by("card_number", "pk")
    batches = Batch.objects.all()
    context = {"card_list": queryset, "batches_list": batches}
    return render(request, template_name, context)


@login_required
def edit_card(request, pk):
    card = Card.objects.get(pk=pk)
    form = CardForm(request.POST or None, request.FILES or None, instance=card)
    if request.method == "POST":
        if form.is_valid():
            form.save()
            url = reverse("cardfactory:card_detail", args=[card.pk])
            return HttpResponseRedirect(url)
    return render(
        request, "cardfactory/edit_card.html", context={"form": form, "card": card}
    )

cardfactory/templates/cardfactory/batch_list.html
{% extends "base.html" %}
{% load static %}
{% block title%}Les Cartes{% endblock title %}
{% block content %}
<h1>Les Lots</h1>

<ol>
{% for batch in batch_list %}
<li><a href="{% url 'cardfactory:card_list_per_batch' batch %}">Lot {{ batch }}</a></li>

{% endfor %}
</ol>
{% endblock content %}

cardfactory/templates/cardfactory/card_compact_list.html
{% extends "base.html" %}
{% load static %}
{% block title%}Les Cartes (vue compacte){% endblock title %}
{% block content %}
<h1>Les Cartes en vue compacte</h1>

{% regroup card_list by lot as batch_list %}
{% for batch in batch_list %}
<h2>Lot {{ batch.grouper }}</h2>
<span class="text-muted">{{batch.list|length}} cartes rédigées</span>
<div class="row">

{% for card in batch.list %}

    <div class="card m-2" style="width: 44rem;">
        <div class="card-body">
            <h3 class="card-title"><a href="{% url 'cardfactory:card_detail' card.pk %}">{{card.title}}</a></h3>
        </div>  <!--card-body-->

    </div>{% endfor %} <!--card-->

</div> <!--row-->
<hr>
{% endfor %} <!--grouper-->
{% endblock content %}

cardfactory/templates/cardfactory/card_detail.html
{% extends "base.html" %}
{% load static %}
{% block title%}{{card.title}}{% endblock title %}
{% block content %}

<div class="card m-4" style="width: 44rem;">
    <div class="card-body">
        <h3 class="card-title">{{card.title}}</h3>
        <img class="card-img-top" src="{% get_media_prefix %}{{card.illustration}}" alt="{{card.illustation_footnote}}">
        <p class="card-text text-muted">{{card.illustation_footnote}}</p>
    </div>  <!--card-body-->
    <hr>
    <div class="card-body">
        <h3 class="card-title">{{card.title}}</h3>
    <p class="card-text">{{card.content|safe}}</p>

    </div> <!--card-body-->
    <div class="card-footer text-muted">Lot {{card.lot}}<a class="btn btn-warning float-right" href="{% url 'cardfactory:edit_card' card.pk %}">Modifier cette carte</a>
    </div>
</div>


{% endblock content %}

cardfactory/templates/cardfactory/card_list.html
{% extends "base.html" %}
{% load static %}
{% block title%}Les Cartes{% endblock title %}
{% block content %}
<h1>Les Cartes</h1>

{% regroup card_list by lot as batch_list %}
{% for batch in batch_list %}
<h2>Lot {{ batch.grouper }}</h2>
<span class="text-muted">{{batch.list|length}} cartes rédigées</span>
<div class="row">
  <div class="col">
{% for card in batch.list %}

    <div class="card m-4" style="width: 44rem;">
        <div class="card-body">
            <h3 class="card-title">{{card.title}}</h3>
            <img class="card-img-top" src="{% get_media_prefix %}{{card.illustration}}" alt="{{card.illustation_footnote}}">
            <p class="card-text text-muted">{{card.illustation_footnote}}</p>
        </div>  <!--card-body-->
        <hr>
        <div class="card-body">
            <h3 class="card-title">{{card.title}}</h3>
        <p class="card-text">{{card.content|safe}}</p>
        </div> <!--card-body-->
        <div class="card-footer text-muted">Lot {{card.lot}}<a class="btn btn-warning float-right" href="{% url 'cardfactory:edit_card' card.pk %}">Modifier cette carte</a></div>
    </div>{% endfor %} <!--card-->
  </div> <!-- first col-->
  <div class="col">
    <h3>Filtrer par lot</h3>
    <ul class="list-group">
    {% for batch in batches_list %}

    <li class="list-group-item"><a href="{% url 'cardfactory:card_list_per_batch' batch.pk %}">Lot {{ batch }}</a></li>

    {% endfor %}
    </ul>
  </div> <!--second col-->

</div> <!--row-->
<hr>
{% endfor %} <!--grouper-->
{% endblock content %}

cardfactory/templates/cardfactory/edit_card.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block title%}Modifier la carte {{card.title}}{% endblock title %}
{% block content %}

<h1>Modifier la carte {{card.title}}</h1>

{% crispy form form.helper %}
{% endblock content %}

cardfactory/templates/cardfactory/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<h1>Le Chantier de la Fresque de la Donnée</h1>
<p><a href="{% url 'cardfactory:card_list' %}">Voir les cartes</a></p>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>

    <!-- boostrap CSS -->

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
 {% load static %}
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <title>{% block title %}Fresque de la Data - Le Chantier{% endblock %}</title>
    <link rel="icon"
        href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>💾</text></svg>">
    {{ form.media }}

    <!--no robots and no surprises-->
    <meta name="robots" content="noindex">
    <meta name="googlebot" content="noindex">
</head>

<body>
<header>

    {% block navbar %}


    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">Fresque de la data - WIP</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'cardfactory:card_list' %}">Les Cartes</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'cardfactory:card_compact_list' %}">Les Cartes (vue compacte)</a>
                </li>
                <!--
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'cardfactory:batch_list' %}">Les Cartes par Lots</a>
                </li>
            -->
                <!--<li class="nav-item">
                    <a class="nav-link" href="#">Actualités</a>
                </li>-->

                <!--<a class="dropdown-item" href="#">Action</a>-->
            </ul>
            <!-- search bar-->
            <ul class="navbar-nav">
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
              </li>
              {% if request.user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'admin:logout' %}">Déconnexion</a>
            </li>
            {% endif %}
            </ul>

        </div>


    </nav>

</header>

    {% endblock %}
    <main role="main" class="container">

    {% block messages %}
        {% if messages %}
                {% for message in messages %}
                <div {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %} role="alert">{{ message }}</div>
                {% endfor %}

        {% endif %}
    {% endblock %}

        {% block content %}{% endblock %}

    </main>


    <!-- Jquery and Popper-->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>

    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
</body>
</html>